### ISSUE TITLE
Add advanced git in advanced page

### ISSUE THREAD

**Issue by charandeepsinghb** [charandeepsinghb/learn-code-contribute#17]
Add a "Git advanced" link in the Advanced page

Link should open a page like one of the beginner page's links

New page including:
- Rebasing
- Git Hooks

Refer to the beginner sections code for the same

**Comment by saakshi002** [comment]
Hi can you assign me this task? @charandeepsinghb

**Comment by Yashhuc** [comment]
I am working on this enhancement.#17

**Comment by Yashhuc** [comment]
Hii.
Please review the following enhancements I made, so that I can commit the changes. #17
![image](https://github.com/charandeepsinghb/learn-code-contribute/assets/120786462/5ebbf7a1-5b19-4c5f-8f30-cf1dc81a00b4)

![image](https://github.com/charandeepsinghb/learn-code-contribute/assets/120786462/39fc382c-6afa-4bb8-a6f6-d22ff295415f)

![image](https://github.com/charandeepsinghb/learn-code-contribute/assets/120786462/f68b9f37-54f8-4a67-8a8b-380e6324b7ca)

**Comment by charandeepsinghb** [comment]
Good

**Comment by charandeepsinghb** [comment]
@saakshi002 You can add more content to the page and fix the issue https://github.com/charandeepsinghb/learn-code-contribute/issues/19

Take reference from this issue and other code.
Add a PR and screenshots I'll assign the issue
Appreciations 👍
